#!/usr/bin/env bash
# This script prints the correct answers about the OSI model

echo "The OSI model is a conceptual model that characterizes the communication functions of a telecommunication system without regard to their underlying internal structure and technology"
echo "From the lowest to the highest level"
