#!/usr/bin/env bash
# This script prints the correct answers about TCP and UDP protocols

echo "It is a protocol that is transferring data in a slow way but surely"
echo "It is a protocol that is transferring data in a fast way and might loss data along in the process"
echo "Have you received boxes x, y, z?"
